import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author songj
 */
public class AdminPage extends javax.swing.JFrame {

    public AdminPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        hospitalBtn = new javax.swing.JButton();
        supplierBtn = new javax.swing.JButton();
        userBtn = new javax.swing.JButton();
        ppeBtn = new javax.swing.JButton();
        transactionBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JLabel();
        mainPanel = new javax.swing.JLayeredPane();
        label = new javax.swing.JLabel();
        longlines = new javax.swing.JLabel();
        form = new javax.swing.JLayeredPane();
        transactionForm = new javax.swing.JLayeredPane();
        jLabel30 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        userForm = new javax.swing.JLayeredPane();
        userFormTitle = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ut1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        ut2 = new javax.swing.JTextField();
        saveUserBtn = new javax.swing.JButton();
        addUserBtn = new javax.swing.JButton();
        ut3 = new javax.swing.JComboBox<>();
        newUserID = new javax.swing.JLabel();
        ppeitemForm = new javax.swing.JLayeredPane();
        ppeItemFormTitle = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t3 = new javax.swing.JComboBox<>();
        t4 = new javax.swing.JLabel();
        addPPEBtn = new javax.swing.JButton();
        savePPEBtn = new javax.swing.JButton();
        hospitalForm = new javax.swing.JLayeredPane();
        jLabel21 = new javax.swing.JLabel();
        hospitalFormTitle = new javax.swing.JLabel();
        ht1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ht2 = new javax.swing.JTextArea();
        ht3 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        newHospitalID = new javax.swing.JLabel();
        addHospitalBtn = new javax.swing.JButton();
        saveHospitalBtn = new javax.swing.JButton();
        supplierForm = new javax.swing.JLayeredPane();
        supplierFormTitle = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        st1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        st2 = new javax.swing.JTextArea();
        st3 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        newSupplierID = new javax.swing.JLabel();
        addSupplierBtn = new javax.swing.JButton();
        saveSupplierBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();
        searchbar = new javax.swing.JTextField();
        table = new javax.swing.JLayeredPane();
        supplierScrollTable = new javax.swing.JScrollPane();
        supplierTable = new javax.swing.JTable();
        hospitalScrollTable = new javax.swing.JScrollPane();
        hospitalTable = new javax.swing.JTable();
        userScrollTable = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();
        ppeItemScrollTable = new javax.swing.JScrollPane();
        ppeItemTable = new javax.swing.JTable();
        transactionScrollTable = new javax.swing.JScrollPane();
        transactionTable = new javax.swing.JTable();
        delBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setAlignmentX(0);
        jPanel1.setAlignmentY(0);

        hospitalBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        hospitalBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospital.png"))); // NOI18N
        hospitalBtn.setText("Hospital");
        hospitalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hospitalBtnActionPerformed(evt);
            }
        });

        supplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        supplierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supplier.png"))); // NOI18N
        supplierBtn.setText("Supplier");
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        userBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        userBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/user.png"))); // NOI18N
        userBtn.setText("User");
        userBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userBtnActionPerformed(evt);
            }
        });

        ppeBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ppeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ppe item.png"))); // NOI18N
        ppeBtn.setText("PPE item");
        ppeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ppeBtnActionPerformed(evt);
            }
        });

        transactionBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transactionBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/transaction.png"))); // NOI18N
        transactionBtn.setText("Transaction");
        transactionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transactionBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Ravie", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ADMIN PAGE");

        logoutBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/log out.png"))); // NOI18N
        logoutBtn.setText("Log Out");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hospitalBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ppeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logoutBtn)
                        .addGap(78, 78, 78))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(logoutBtn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hospitalBtn)
                    .addComponent(supplierBtn)
                    .addComponent(userBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ppeBtn)
                    .addComponent(transactionBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        label.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label.setText("HOSPITAL");

        longlines.setText("_______________________________________________________________________________");

        form.setLayout(new java.awt.CardLayout());

        jLabel30.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel30.setText("New Transaction Form");

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setText("Save Changes");

        jButton5.setBackground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Add New");

        transactionForm.setLayer(jLabel30, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transactionForm.setLayer(jButton7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        transactionForm.setLayer(jButton5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout transactionFormLayout = new javax.swing.GroupLayout(transactionForm);
        transactionForm.setLayout(transactionFormLayout);
        transactionFormLayout.setHorizontalGroup(
            transactionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFormLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(transactionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionFormLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionFormLayout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jButton7)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        transactionFormLayout.setVerticalGroup(
            transactionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionFormLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(194, 194, 194)
                .addGroup(transactionFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton7))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        form.add(transactionForm, "card2");

        userFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        userFormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userFormTitle.setText("New User Form");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setText("User ID:");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setText("Name:");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setText("Password:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setText("Type of User:");

        saveUserBtn.setBackground(new java.awt.Color(51, 51, 51));
        saveUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        saveUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveUserBtn.setText("Save Changes");
        saveUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUserBtnActionPerformed(evt);
            }
        });

        addUserBtn.setBackground(new java.awt.Color(51, 51, 51));
        addUserBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addUserBtn.setForeground(new java.awt.Color(255, 255, 255));
        addUserBtn.setText("Add New");
        addUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserBtnActionPerformed(evt);
            }
        });

        ut3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Staff" }));

        newUserID.setText("Code here");

        userForm.setLayer(userFormTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(ut1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(jLabel17, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(jLabel18, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(jLabel19, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(ut2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(saveUserBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(addUserBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(ut3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        userForm.setLayer(newUserID, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout userFormLayout = new javax.swing.GroupLayout(userForm);
        userForm.setLayout(userFormLayout);
        userFormLayout.setHorizontalGroup(
            userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormLayout.createSequentialGroup()
                .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(saveUserBtn)
                    .addComponent(addUserBtn)
                    .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(userFormLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ut2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ut1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(userFormLayout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(userFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(userFormLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ut3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        userFormLayout.setVerticalGroup(
            userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userFormLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(userFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(newUserID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(ut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(userFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ut3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addUserBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveUserBtn)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        form.add(userForm, "card2");

        ppeItemFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ppeItemFormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ppeItemFormTitle.setText("New PPE Item Form");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel26.setText("Item ID:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel27.setText("Item Name:");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel28.setText("Supplier ID:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel29.setText("Quantity In Stock:");


            t4.setText("100");

            addPPEBtn.setBackground(new java.awt.Color(51, 51, 51));
            addPPEBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            addPPEBtn.setForeground(new java.awt.Color(255, 255, 255));
            addPPEBtn.setText("Add New");
            addPPEBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addPPEBtnActionPerformed(evt);
                }
            });

            savePPEBtn.setBackground(new java.awt.Color(51, 51, 51));
            savePPEBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            savePPEBtn.setForeground(new java.awt.Color(255, 255, 255));
            savePPEBtn.setText("Save Changes");
            savePPEBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    savePPEBtnActionPerformed(evt);
                }
            });

            ppeitemForm.setLayer(ppeItemFormTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(jLabel26, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(t2, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(jLabel27, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(jLabel28, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(jLabel29, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(t1, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(t3, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(t4, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(addPPEBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
            ppeitemForm.setLayer(savePPEBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout ppeitemFormLayout = new javax.swing.GroupLayout(ppeitemForm);
            ppeitemForm.setLayout(ppeitemFormLayout);
            ppeitemFormLayout.setHorizontalGroup(
                ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ppeitemFormLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(savePPEBtn)
                        .addComponent(addPPEBtn))
                    .addGap(23, 23, 23))
                .addGroup(ppeitemFormLayout.createSequentialGroup()
                    .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppeitemFormLayout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ppeitemFormLayout.createSequentialGroup()
                            .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGap(42, 42, 42)
                            .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(ppeitemFormLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(ppeItemFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(71, Short.MAX_VALUE))
            );
            ppeitemFormLayout.setVerticalGroup(
                ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(ppeitemFormLayout.createSequentialGroup()
                    .addComponent(ppeItemFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ppeitemFormLayout.createSequentialGroup()
                            .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(9, 9, 9)
                            .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel27)
                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel28)
                                .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(ppeitemFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t4)
                        .addComponent(jLabel29))
                    .addGap(15, 15, 15)
                    .addComponent(addPPEBtn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(savePPEBtn)
                    .addContainerGap(107, Short.MAX_VALUE))
            );

            form.add(ppeitemForm, "card4");

            jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel21.setText("Hospital ID:");

            hospitalFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            hospitalFormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            hospitalFormTitle.setText("New Hospital Form");

            jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel22.setText("Name:");

            jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel23.setText("Address:");

            ht2.setColumns(20);
            ht2.setRows(5);
            jScrollPane6.setViewportView(ht2);

            jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel24.setText("Phone Number:");

            newHospitalID.setText("Code here");

            addHospitalBtn.setBackground(new java.awt.Color(51, 51, 51));
            addHospitalBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            addHospitalBtn.setForeground(new java.awt.Color(255, 255, 255));
            addHospitalBtn.setText("Add New");
            addHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addHospitalBtnActionPerformed(evt);
                }
            });

            saveHospitalBtn.setBackground(new java.awt.Color(51, 51, 51));
            saveHospitalBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            saveHospitalBtn.setForeground(new java.awt.Color(255, 255, 255));
            saveHospitalBtn.setText("Save Changes");
            saveHospitalBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveHospitalBtnActionPerformed(evt);
                }
            });

            hospitalForm.setLayer(jLabel21, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(hospitalFormTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(ht1, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(jLabel22, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(jLabel23, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(ht3, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(jLabel24, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(newHospitalID, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(addHospitalBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
            hospitalForm.setLayer(saveHospitalBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout hospitalFormLayout = new javax.swing.GroupLayout(hospitalForm);
            hospitalForm.setLayout(hospitalFormLayout);
            hospitalFormLayout.setHorizontalGroup(
                hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hospitalFormLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(hospitalFormTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(hospitalFormLayout.createSequentialGroup()
                            .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel24))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                            .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(newHospitalID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                .addComponent(ht1))
                            .addGap(0, 59, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hospitalFormLayout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(addHospitalBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(saveHospitalBtn, javax.swing.GroupLayout.Alignment.TRAILING))))
                    .addContainerGap())
            );
            hospitalFormLayout.setVerticalGroup(
                hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hospitalFormLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(hospitalFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel21)
                        .addComponent(newHospitalID))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ht1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22))
                    .addGap(18, 18, 18)
                    .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel23)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(21, 21, 21)
                    .addGroup(hospitalFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ht3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel24))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(addHospitalBtn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(saveHospitalBtn)
                    .addContainerGap(40, Short.MAX_VALUE))
            );

            form.add(hospitalForm, "card4");

            supplierFormTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
            supplierFormTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
            supplierFormTitle.setText("New Supplier Form");

            jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel12.setText("Supplier ID:");

            jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel7.setText("Name:");

            jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel13.setText("Address:");

            st2.setColumns(20);
            st2.setRows(5);
            jScrollPane4.setViewportView(st2);

            jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel14.setText("Phone Number:");

            newSupplierID.setText("Code here");

            addSupplierBtn.setBackground(new java.awt.Color(51, 51, 51));
            addSupplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            addSupplierBtn.setForeground(new java.awt.Color(255, 255, 255));
            addSupplierBtn.setText("Add New");
            addSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    addSupplierBtnActionPerformed(evt);
                }
            });

            saveSupplierBtn.setBackground(new java.awt.Color(51, 51, 51));
            saveSupplierBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            saveSupplierBtn.setForeground(new java.awt.Color(255, 255, 255));
            saveSupplierBtn.setText("Save Changes");
            saveSupplierBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    saveSupplierBtnActionPerformed(evt);
                }
            });

            supplierForm.setLayer(supplierFormTitle, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(jLabel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(st1, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(st3, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(newSupplierID, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(addSupplierBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
            supplierForm.setLayer(saveSupplierBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout supplierFormLayout = new javax.swing.GroupLayout(supplierForm);
            supplierForm.setLayout(supplierFormLayout);
            supplierFormLayout.setHorizontalGroup(
                supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(supplierFormLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(saveSupplierBtn)
                            .addComponent(addSupplierBtn)
                            .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(supplierFormLayout.createSequentialGroup()
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(newSupplierID, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(supplierFormLayout.createSequentialGroup()
                                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel14))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                        .addComponent(st1)
                                        .addGroup(supplierFormLayout.createSequentialGroup()
                                            .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(0, 0, Short.MAX_VALUE))))))
                        .addComponent(supplierFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(57, Short.MAX_VALUE))
            );
            supplierFormLayout.setVerticalGroup(
                supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(supplierFormLayout.createSequentialGroup()
                    .addComponent(supplierFormTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(25, 25, 25)
                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(newSupplierID))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(st1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(supplierFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(st3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(addSupplierBtn)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(saveSupplierBtn)
                    .addContainerGap(43, Short.MAX_VALUE))
            );

            form.add(supplierForm, "card3");

            jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            jLabel9.setText("Enter the ID here:");

            searchBtn.setBackground(new java.awt.Color(51, 51, 51));
            searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            searchBtn.setForeground(new java.awt.Color(255, 255, 255));
            searchBtn.setText("Search");
            searchBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    searchBtnActionPerformed(evt);
                }
            });

            table.setLayout(new java.awt.CardLayout());

            supplierTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            supplierScrollTable.setViewportView(supplierTable);

            table.add(supplierScrollTable, "card2");

            hospitalTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            hospitalScrollTable.setViewportView(hospitalTable);

            table.add(hospitalScrollTable, "card3");

            userTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            userScrollTable.setViewportView(userTable);

            table.add(userScrollTable, "card2");

            ppeItemTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            ppeItemScrollTable.setViewportView(ppeItemTable);

            table.add(ppeItemScrollTable, "card2");

            transactionTable.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {

                },
                new String [] {

                }
            ));
            transactionScrollTable.setViewportView(transactionTable);

            table.add(transactionScrollTable, "card2");

            delBtn.setBackground(new java.awt.Color(153, 0, 0));
            delBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            delBtn.setForeground(new java.awt.Color(255, 255, 255));
            delBtn.setText("Delete");
            delBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    delBtnActionPerformed(evt);
                }
            });

            editBtn.setBackground(new java.awt.Color(51, 51, 51));
            editBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
            editBtn.setForeground(new java.awt.Color(255, 255, 255));
            editBtn.setText("Edit");
            editBtn.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    editBtnActionPerformed(evt);
                }
            });

            mainPanel.setLayer(label, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(longlines, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(form, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(searchBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(searchbar, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(table, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(delBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);
            mainPanel.setLayer(editBtn, javax.swing.JLayeredPane.DEFAULT_LAYER);

            javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
            mainPanel.setLayout(mainPanelLayout);
            mainPanelLayout.setHorizontalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(searchBtn))
                        .addComponent(longlines, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(2474, 2474, 2474))
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 923, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(275, 275, 275)
                            .addComponent(editBtn)
                            .addGap(18, 18, 18)
                            .addComponent(delBtn)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            mainPanelLayout.setVerticalGroup(
                mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(label)
                    .addGap(12, 12, 12)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(delBtn)
                                .addComponent(editBtn)))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(searchbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(searchBtn))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(longlines)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(form, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(23, Short.MAX_VALUE))
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 952, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    //MAIN PANELS BUTTON
    private void hospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hospitalBtnActionPerformed
        supplierForm.setVisible(false);
        hospitalForm.setVisible(true);
        transactionForm.setVisible(false);
        userForm.setVisible(false);
        ppeitemForm.setVisible(false);
        
        try {
            String newID = filefunction.generateNewID("hospitals.txt");
            newHospitalID.setText("H-"+newID);
        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to generate new Hospital ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        label.setText("HOSPITAL MENU");
        saveHospitalBtn.setVisible(false);
        addHospitalBtn.setVisible(true);
        
        supplierScrollTable.setVisible(false);  
        hospitalScrollTable.setVisible(true); 
        userScrollTable.setVisible(false);      
        ppeItemScrollTable.setVisible(false);
        
        DefaultTableModel model1 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        String[] ColHeadings = {"Hospital ID", "Name", "Address", "Phone Number"};
        model1.setColumnIdentifiers(ColHeadings);
        hospitalTable.setModel(model1);
        model1.setRowCount(0);
        hospitalTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        try {
            filefunction.loadDataFromFile("hospitals.txt",model1);
        } catch (Exception ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to load hospital data.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_hospitalBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        supplierForm.setVisible(true);
        hospitalForm.setVisible(false);
        transactionForm.setVisible(false);
        userForm.setVisible(false);
        ppeitemForm.setVisible(false);
        
        try {
            String newID = filefunction.generateNewID("suppliers.txt");
            newSupplierID.setText("S-"+newID);
        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to generate new Supplier ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        label.setText("SUPPLIER MENU");
        saveSupplierBtn.setVisible(false);
        addSupplierBtn.setVisible(true);
        
        supplierScrollTable.setVisible(true);  
        hospitalScrollTable.setVisible(false); 
        userScrollTable.setVisible(false);      
        ppeItemScrollTable.setVisible(false);
        
        DefaultTableModel model2 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        String[] ColHeadings = {"Supplier ID", "Name", "Address", "Phone Number"};
        model2.setColumnIdentifiers(ColHeadings);
        supplierTable.setModel(model2);
        model2.setRowCount(0);
        supplierTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        try {
            filefunction.loadDataFromFile("suppliers.txt",model2);
        } catch (Exception ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to load hospital data.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void userBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userBtnActionPerformed
        supplierForm.setVisible(false);
        hospitalForm.setVisible(false);
        transactionForm.setVisible(false);
        userForm.setVisible(true);
        ppeitemForm.setVisible(false);
        
        try {
        String newID = filefunction.generateNewID("users.txt");
        newSupplierID.setText("Staff-"+newID);
        } catch (IOException ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Failed to generate new User ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        label.setText("USER MENU");
        saveUserBtn.setVisible(false);
        addUserBtn.setVisible(true);
        
        supplierScrollTable.setVisible(false);  
        hospitalScrollTable.setVisible(false); 
        userScrollTable.setVisible(true);      
        ppeItemScrollTable.setVisible(false);
        
        DefaultTableModel model3 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        String[] ColHeadings = {"User ID", "Name", "Password", "Type of user"};
        model3.setColumnIdentifiers(ColHeadings);
        userTable.setModel(model3);
        model3.setRowCount(0);
        userTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        try {
            filefunction.loadDataFromFile("users.txt",model3);
        } catch (Exception ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_userBtnActionPerformed

    private void ppeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ppeBtnActionPerformed
        supplierForm.setVisible(false);
        hospitalForm.setVisible(false);
        transactionForm.setVisible(false);
        userForm.setVisible(false);
        ppeitemForm.setVisible(true);
        
        label.setText("PPE ITEM MENU");
        savePPEBtn.setVisible(false);
        addPPEBtn.setVisible(true);
        
        supplierScrollTable.setVisible(false);  
        hospitalScrollTable.setVisible(false); 
        userScrollTable.setVisible(false);      
        ppeItemScrollTable.setVisible(true);
        
        t3.removeAllItems();
        List<String> allSupplierIDs = filefunction.GET_ALL_ID("suppliers.txt");
        for (String id : allSupplierIDs) {
            t3.addItem(id);
        }
        
        DefaultTableModel model4 = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               //all cells false
               return false;
            }
        };
        String[] ColHeadings = {"Item ID", "Item Name", "Supplier ID", "Quantity in stock"};
        model4.setColumnIdentifiers(ColHeadings);
        ppeItemTable.setModel(model4);
        model4.setRowCount(0);
        ppeItemTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        try {
            filefunction.loadDataFromFile("ppe.txt",model4);
        } catch (Exception ex) {
            Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ppeBtnActionPerformed

    private void transactionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transactionBtnActionPerformed
        supplierForm.setVisible(false);
        hospitalForm.setVisible(false);
        transactionForm.setVisible(true);
        userForm.setVisible(false);
        ppeitemForm.setVisible(false);
        label.setText("TRANSACTION MENU");
    }//GEN-LAST:event_transactionBtnActionPerformed

    //ADD NEW DATA
    private void addPPEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPPEBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) ppeItemTable.getModel();
        String input1 = t1.getText();
        String input2 = t2.getText();
        String input3 = (String) t3.getSelectedItem();
        String input4 = "100";
        if (!input1.isEmpty() && !input2.isEmpty() && !input3.isEmpty()) {
            filefunction.ADD_DATA("ppe.txt",model, input1, input2, input3, input4);
            JOptionPane.showMessageDialog(this, "PPE item data submitted", "Message", JOptionPane.INFORMATION_MESSAGE);

            //Clear all TextField contents
            t1.setText("");
            t2.setText("");
        }
    }//GEN-LAST:event_addPPEBtnActionPerformed

    private void addHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHospitalBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) hospitalTable.getModel();
        String input1 = ht1.getText();
        String input2 = ht2.getText();
        String input3 = ht3.getText();
        if (!input1.isEmpty() && !input2.isEmpty() && !input3.isEmpty()) {
            filefunction.ADD_DATA("hospitals.txt",model, input1, input2, input3);
            JOptionPane.showMessageDialog(this, "Hospital data submitted", "Message", JOptionPane.INFORMATION_MESSAGE);

            // Clear all TextField contents
            ht1.setText("");
            ht2.setText("");
            ht3.setText("");
            
            try {
                String newID = filefunction.generateNewID("hospitals.txt");
                newHospitalID.setText("H-"+newID);
            } catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to generate new Hospital ID.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_addHospitalBtnActionPerformed

    private void addUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) userTable.getModel();
        String input1 = ut1.getText();
        String input2 = ut2.getText();
        String input3 = (String) ut3.getSelectedItem();
        if (!input1.isEmpty() && !input2.isEmpty() && !input3.isEmpty()) {
            filefunction.ADD_DATA("users.txt",model, input1, input2, input3);
            JOptionPane.showMessageDialog(this, "User data submitted", "Message", JOptionPane.INFORMATION_MESSAGE);

            // Clear all TextField contents
            ut1.setText("");
            ut2.setText("");

        }
    }//GEN-LAST:event_addUserBtnActionPerformed

    private void addSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSupplierBtnActionPerformed
        DefaultTableModel model = (DefaultTableModel) supplierTable.getModel();
        String input1 = st1.getText();
        String input2 = st2.getText();
        String input3 = st3.getText();
        if (!input1.isEmpty() && !input2.isEmpty() && !input3.isEmpty()) {
            filefunction.ADD_DATA("suppliers.txt",model, input1, input2, input3);
            JOptionPane.showMessageDialog(this, "Supplier data submitted", "Message", JOptionPane.INFORMATION_MESSAGE);

            // Clear all TextField contents
            st1.setText("");
            st2.setText("");
            st3.setText("");
            
            try {
                String newID = filefunction.generateNewID("suppliers.txt");
                newSupplierID.setText("S-"+newID);
            } catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to generate new Hospital ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_addSupplierBtnActionPerformed

    //SAVE CHANGES
    private void saveUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUserBtnActionPerformed
        addUserBtn.setVisible(true);
        saveUserBtn.setVisible(false);
        
        DefaultTableModel model = (DefaultTableModel)userTable.getModel();
        int sRow = userTable.getSelectedRow();
        model.setValueAt(newUserID.getText(),sRow,0);
        model.setValueAt(ut1.getText(),sRow,1);
        model.setValueAt(ut2.getText(),sRow,2);
        model.setValueAt(ut3.getSelectedItem(),sRow,3);
        
        // Prepare data for file update
        String[] newData = new String[4];
        newData[0] = newUserID.getText();
        newData[1] = ut1.getText();
        newData[2] = ut2.getText();
        newData[3] = (String) ut3.getSelectedItem();
        
        // Call file update method
        boolean actionDone = filefunction.EDIT_DATA("users.txt", newData);
        
        if (actionDone) {
            JOptionPane.showMessageDialog(rootPane, "User Data updated successfully", "Update Result", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear all TextFields
            try {
                String newID = filefunction.generateNewID("users.txt");
                newHospitalID.setText("Staff-"+newID);
            } catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to generate new user ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ut1.setText("");
            ut2.setText("");
            ut3.setSelectedItem(0);
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to update data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveUserBtnActionPerformed

    private void saveSupplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveSupplierBtnActionPerformed
        addSupplierBtn.setVisible(true);
        saveSupplierBtn.setVisible(false);
        
        DefaultTableModel model = (DefaultTableModel)supplierTable.getModel();
        int sRow = supplierTable.getSelectedRow();
        model.setValueAt(newSupplierID.getText(),sRow,0);
        model.setValueAt(st1.getText(),sRow,1);
        model.setValueAt(st2.getText(),sRow,2);
        model.setValueAt(st3.getText(),sRow,3);
        
        // Prepare data for file update
        String[] newData = new String[4];
        newData[0] = newSupplierID.getText();
        newData[1] = st1.getText();
        newData[2] = st2.getText();
        newData[3] = st3.getText();
        
        // Call file update method
        boolean actionDone = filefunction.EDIT_DATA("suppliers.txt", newData);
        
        if (actionDone) {
            JOptionPane.showMessageDialog(rootPane, "Supplier Data updated successfully", "Update Result", JOptionPane.INFORMATION_MESSAGE);
            
            try {
                String newID = filefunction.generateNewID("suppliers.txt");
                newSupplierID.setText("S-"+newID);
            } catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to generate new Supplier ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            st1.setText("");
            st2.setText("");
            st3.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to update data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveSupplierBtnActionPerformed

    private void saveHospitalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveHospitalBtnActionPerformed
        addHospitalBtn.setVisible(true);
        saveHospitalBtn.setVisible(false);
        
        DefaultTableModel model = (DefaultTableModel)hospitalTable.getModel();
        int sRow = hospitalTable.getSelectedRow();
        model.setValueAt(newHospitalID.getText(),sRow,0);
        model.setValueAt(ht1.getText(),sRow,1);
        model.setValueAt(ht2.getText(),sRow,2);
        model.setValueAt(ht3.getText(),sRow,3);
        
        // Prepare data for file update
        String[] newData = new String[4];
        newData[0] = newHospitalID.getText();
        newData[1] = ht1.getText();
        newData[2] = ht2.getText();
        newData[3] = ht3.getText();
        
        // Call file update method
        boolean actionDone = filefunction.EDIT_DATA("hospitals.txt", newData);
        
        if (actionDone) {
            JOptionPane.showMessageDialog(rootPane, "Hospital Data updated successfully", "Update Result", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear all TextFields
            try {
                String newID = filefunction.generateNewID("hospitals.txt");
                newHospitalID.setText("H-"+newID);
            } catch (IOException ex) {
                Logger.getLogger(AdminPage.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "Failed to generate new Hospital ID.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            ht1.setText("");
            ht2.setText("");
            ht3.setText("");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to update data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_saveHospitalBtnActionPerformed

    private void savePPEBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePPEBtnActionPerformed
        addPPEBtn.setVisible(true);
        savePPEBtn.setVisible(false);
        
        DefaultTableModel model = (DefaultTableModel)ppeItemTable.getModel();
        int sRow = ppeItemTable.getSelectedRow();
        model.setValueAt(t1.getText(),sRow,0);
        model.setValueAt(t2.getText(),sRow,1);
        model.setValueAt(t3.getSelectedItem(),sRow,2);
        model.setValueAt(t4.getText(),sRow,3);
        
        // Prepare data for file update
        String[] newData = new String[4];
        newData[0] = t1.getText();
        newData[1] = t2.getText();
        newData[2] = (String)t3.getSelectedItem();
        newData[3] = t4.getText();
        
        // Call file update method
        boolean actionDone = filefunction.EDIT_DATA("ppe.txt", newData);
        
        if (actionDone) {
            JOptionPane.showMessageDialog(rootPane, "PPE Item Data updated successfully", "Update Result", JOptionPane.INFORMATION_MESSAGE);
            
            t1.setText("");
            t2.setText("");
            t3.setSelectedItem(0);
            t4.setText("100");
        } else {
            JOptionPane.showMessageDialog(rootPane, "Failed to update data", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_savePPEBtnActionPerformed

    //EDIT, SEARCH AND DELETE
    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        try {
            if (hospitalScrollTable.isVisible()) {
                DefaultTableModel model1 = (DefaultTableModel) hospitalTable.getModel();
                int sRow = hospitalTable.getSelectedRow();
                if (sRow >= 0) {
                    String hospitalID = model1.getValueAt(sRow, 0).toString();
                    filefunction.DELETE_DATA("hospitals.txt", hospitalID, this);  // Pass the parent component 'this'
                    model1.removeRow(sRow);  // Remove the row from the table
                    JOptionPane.showMessageDialog(this, "Hospital record deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new IllegalStateException("Please select a row to delete.");
                }
            } else if (supplierScrollTable.isVisible()) {
                DefaultTableModel model2 = (DefaultTableModel) supplierTable.getModel();
                int sRow = supplierTable.getSelectedRow();
                if (sRow >= 0) {
                    String supplierID = model2.getValueAt(sRow, 0).toString();
                    filefunction.DELETE_DATA("suppliers.txt", supplierID, this);  // Pass the parent component 'this'
                    model2.removeRow(sRow);
                    JOptionPane.showMessageDialog(this, "Supplier record deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new IllegalStateException("Please select a row to delete.");
                }
            } else if (userScrollTable.isVisible()) {
                DefaultTableModel model3 = (DefaultTableModel) userTable.getModel();
                int sRow = userTable.getSelectedRow();
                if (sRow >= 0) {
                    String userID = model3.getValueAt(sRow, 0).toString();
                    filefunction.DELETE_DATA("users.txt", userID, this);  // Pass the parent component 'this'
                    model3.removeRow(sRow);
                    JOptionPane.showMessageDialog(this, "User record deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new IllegalStateException("Please select a row to delete.");
                }
            } else if (ppeItemScrollTable.isVisible()) {
                DefaultTableModel model4 = (DefaultTableModel) ppeItemTable.getModel();
                int sRow = ppeItemTable.getSelectedRow();
                if (sRow >= 0) {
                    String itemID = model4.getValueAt(sRow, 0).toString();
                    filefunction.DELETE_DATA("ppe.txt", itemID, this);  // Pass the parent component 'this'
                    model4.removeRow(sRow);
                    JOptionPane.showMessageDialog(this, "PPE Item record deleted successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    throw new IllegalStateException("Please select a row to delete.");
                }
            }
        } catch (IllegalStateException ex) {
            // Handle the exception here
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if (hospitalScrollTable.isVisible()) {
            DefaultTableModel model1 = (DefaultTableModel) hospitalTable.getModel();
            String search = searchbar.getText();
            String ID = filefunction.SEARCH_DATA("hospitals.txt", search,this);
            if (ID != null) {
                for (int i = 0; i < model1.getRowCount(); i++) {
                    if (model1.getValueAt(i, 0).toString().equals(search)) {
                        hospitalTable.setRowSelectionInterval(i, i);
                        hospitalTable.scrollRectToVisible(hospitalTable.getCellRect(i, 0, true)); //scroll to the area that can see the row
                        break;
                    }
                }
            }
        } else if (supplierScrollTable.isVisible()) {
            DefaultTableModel model2 = (DefaultTableModel) supplierTable.getModel();
            String search = searchbar.getText();
             String ID = filefunction.SEARCH_DATA("suppliers.txt", search,this);
             if (ID != null) {
                for (int i = 0; i < model2.getRowCount(); i++) {
                    if (model2.getValueAt(i, 0).toString().equals(search)) {
                        supplierTable.setRowSelectionInterval(i, i);
                        supplierTable.scrollRectToVisible(supplierTable.getCellRect(i, 0, true)); 
                        break;
                    }
                }
            }
        } else if (userScrollTable.isVisible()) {
            DefaultTableModel model3 = (DefaultTableModel) userTable.getModel();
            String search = searchbar.getText();
            String ID = filefunction.SEARCH_DATA("users.txt", search,this);
            if (ID != null) {
                for (int i = 0; i < model3.getRowCount(); i++) {
                    if (model3.getValueAt(i, 0).toString().equals(search)) {
                        userTable.setRowSelectionInterval(i, i);
                        userTable.scrollRectToVisible(userTable.getCellRect(i, 0, true)); 
                        break;
                    }
                }
            }
        } else if (ppeItemScrollTable.isVisible()) {
            DefaultTableModel model4 = (DefaultTableModel) ppeItemTable.getModel();
            String search = searchbar.getText();
            String ID = filefunction.SEARCH_DATA("ppe.txt", search,this);
            if (ID != null) {
                for (int i = 0; i < model4.getRowCount(); i++) {
                    if (model4.getValueAt(i, 0).toString().equals(search)) {
                        ppeItemTable.setRowSelectionInterval(i, i);
                        ppeItemTable.scrollRectToVisible(ppeItemTable.getCellRect(i, 0, true)); 
                        break;
                    }
                }
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        if (hospitalScrollTable.isVisible()) {
            hospitalFormTitle.setText("Edit Hospital Form");
            saveHospitalBtn.setVisible(true);
            addHospitalBtn.setVisible(false);

            DefaultTableModel model1 = (DefaultTableModel) hospitalTable.getModel();
            int sRow = hospitalTable.getSelectedRow();
            if (sRow >= 0) {
                newHospitalID.setText(model1.getValueAt(sRow, 0).toString());
                ht1.setText(model1.getValueAt(sRow, 1).toString());
                ht2.setText(model1.getValueAt(sRow, 2).toString());
                ht3.setText(model1.getValueAt(sRow, 3).toString());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select a row");
            }
        } else if (supplierScrollTable.isVisible()) {
            System.out.println("hihi");
            supplierFormTitle.setText("Edit Supplier Form");
            saveSupplierBtn.setVisible(true);
            addSupplierBtn.setVisible(false);
            DefaultTableModel model2 = (DefaultTableModel) supplierTable.getModel();
            int sRow = supplierTable.getSelectedRow();
            if (sRow >= 0) {
                newSupplierID.setText(model2.getValueAt(sRow, 0).toString());
                st1.setText(model2.getValueAt(sRow, 1).toString());
                st2.setText(model2.getValueAt(sRow, 2).toString());
                st3.setText(model2.getValueAt(sRow, 3).toString());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select a row");
            }
        } else if (userScrollTable.isVisible()) {
            userFormTitle.setText("Edit User Form");
            saveUserBtn.setVisible(true);
            addUserBtn.setVisible(false);
            DefaultTableModel model3 = (DefaultTableModel) userTable.getModel();
            int sRow = userTable.getSelectedRow();
            if (sRow >= 0) {
                newUserID.setText(model3.getValueAt(sRow, 0).toString());
                ut1.setText(model3.getValueAt(sRow, 1).toString());
                ut2.setText(model3.getValueAt(sRow, 2).toString());
                ut3.setSelectedItem(model3.getValueAt(sRow, 3).toString());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select a row");
            }
        }
        else if (ppeItemScrollTable.isVisible()) {
            ppeItemFormTitle.setText("Edit PPE Item Form");
            savePPEBtn.setVisible(true); 
            addPPEBtn.setVisible(false);
            DefaultTableModel model4 = (DefaultTableModel) ppeItemTable.getModel();
            int sRow = ppeItemTable.getSelectedRow();
            if (sRow >= 0) {
                t1.setText(model4.getValueAt(sRow, 0).toString());
                t2.setText(model4.getValueAt(sRow, 1).toString());
                t3.setSelectedItem(model4.getValueAt(sRow, 2).toString());
                t4.setText(model4.getValueAt(sRow, 3).toString());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please select a row");
            }
        } else if ("TRANSACTION MENU".equals(label)) {
        }
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new filefunction(() ->{
                    new AdminPage().setVisible(true);
                });
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHospitalBtn;
    private javax.swing.JButton addPPEBtn;
    private javax.swing.JButton addSupplierBtn;
    private javax.swing.JButton addUserBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLayeredPane form;
    private javax.swing.JButton hospitalBtn;
    private javax.swing.JLayeredPane hospitalForm;
    private javax.swing.JLabel hospitalFormTitle;
    private javax.swing.JScrollPane hospitalScrollTable;
    private javax.swing.JTable hospitalTable;
    private javax.swing.JTextField ht1;
    private javax.swing.JTextArea ht2;
    private javax.swing.JTextField ht3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel label;
    private javax.swing.JLabel logoutBtn;
    private javax.swing.JLabel longlines;
    private javax.swing.JLayeredPane mainPanel;
    private javax.swing.JLabel newHospitalID;
    private javax.swing.JLabel newSupplierID;
    private javax.swing.JLabel newUserID;
    private javax.swing.JButton ppeBtn;
    private javax.swing.JLabel ppeItemFormTitle;
    private javax.swing.JScrollPane ppeItemScrollTable;
    private javax.swing.JTable ppeItemTable;
    private javax.swing.JLayeredPane ppeitemForm;
    private javax.swing.JButton saveHospitalBtn;
    private javax.swing.JButton savePPEBtn;
    private javax.swing.JButton saveSupplierBtn;
    private javax.swing.JButton saveUserBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchbar;
    private javax.swing.JTextField st1;
    private javax.swing.JTextArea st2;
    private javax.swing.JTextField st3;
    private javax.swing.JButton supplierBtn;
    private javax.swing.JLayeredPane supplierForm;
    private javax.swing.JLabel supplierFormTitle;
    private javax.swing.JScrollPane supplierScrollTable;
    private javax.swing.JTable supplierTable;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JComboBox<String> t3;
    private javax.swing.JLabel t4;
    private javax.swing.JLayeredPane table;
    private javax.swing.JButton transactionBtn;
    private javax.swing.JLayeredPane transactionForm;
    private javax.swing.JScrollPane transactionScrollTable;
    private javax.swing.JTable transactionTable;
    private javax.swing.JButton userBtn;
    private javax.swing.JLayeredPane userForm;
    private javax.swing.JLabel userFormTitle;
    private javax.swing.JScrollPane userScrollTable;
    private javax.swing.JTable userTable;
    private javax.swing.JTextField ut1;
    private javax.swing.JTextField ut2;
    private javax.swing.JComboBox<String> ut3;
    // End of variables declaration//GEN-END:variables
}
